[versions]
agp = "8.5.0"
bitcoinKmp = "0.19.0"
cbor = "0.9"
krypto = "4.0.10"
secp256k1Kmp = "0.19.0"
web3j-core-android = "5.0.0"
coreVersion = "1.58.0.0"
curve25519Android = "0.5.0"
gson = "2.10.1"
guava = "33.2.1-android"
kotlin = "2.0.0"
kotlinUnsigned = "v2.1"
ktor = "2.3.12"
kotlinxCoroutinesCore = "1.8.1"
kotlinxSerializationJson = "1.6.3"
mockitoCore = "5.2.0"
okhttp = "5.0.0-alpha.14"
okio = "3.9.0"
retrofit = "2.11.0"
rxandroid = "2.1.1"
rxjava = "2.2.21"
rxkotlin = "2.4.0"
testng = "6.9.6"
bouncycastle="1.82"

[libraries]
adapter-rxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofit" }
bitcoin-kmp = { module = "fr.acinq.bitcoin:bitcoin-kmp", version.ref = "bitcoinKmp" }
cbor = { module = "co.nstant.in:cbor", version.ref = "cbor" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
krypto = { module = "com.soywiz.korlibs.krypto:krypto", version.ref = "krypto" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
secp256k1-kmp = { module = "fr.acinq.secp256k1:secp256k1-kmp", version.ref = "secp256k1Kmp" }
secp256k1-kmp-jni-android = { module = "fr.acinq.secp256k1:secp256k1-kmp-jni-android", version.ref = "secp256k1Kmp" }
secp256k1-kmp-jni-jvm = { module = "fr.acinq.secp256k1:secp256k1-kmp-jni-jvm", version.ref = "secp256k1Kmp" }
web3j-core-android = { module = "org.web3j:core", version.ref = "web3j-core-android" }
curve25519-android = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-unsigned = { module = "com.github.kotlin-graphics:kotlin-unsigned", version.ref = "kotlinUnsigned" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-core = {module = "io.ktor:ktor-client-core", version.ref = "ktor"}
ktor-client-cio = {module = "io.ktor:ktor-client-cio", version.ref = "ktor"}
ktor-client-serialization = {module = "io.ktor:ktor-client-serialization", version.ref = "ktor"}
ktor-client-json = {module = "io.ktor:ktor-client-json" , version.ref="ktor"}
ktor-client-darwin = {module = "io.ktor:ktor-client-darwin", version.ref="ktor"}
ktor-client-content-negotiation = {module = "io.ktor:ktor-client-content-negotiation", version.ref="ktor"}
ktor-serialization-kotlinx-json = {module = "io.ktor:ktor-serialization-kotlinx-json", version.ref ="ktor"}
ktor-client-logging = {module = "io.ktor:ktor-client-logging", version.ref = "ktor"}
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
prov = { module = "com.madgag.spongycastle:prov", version.ref = "coreVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }
rxkotlin = { module = "io.reactivex.rxjava2:rxkotlin", version.ref = "rxkotlin" }
spongycastle-core = { module = "com.madgag.spongycastle:core", version.ref = "coreVersion" }
testng = { group = "org.testng", name = "testng", version.ref = "testng" }
kotlinx-coroutines-test = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesCore"}


[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
